# 按当前视频所在文件夹名称缓存播放速度

# 是否启用此脚本；yes=启用，no=禁用
enabled=yes

# 播放速度缓存文件路径；~~ 表示 mpv 配置目录 portable_config
cache_path=~~/_cache/folder-speed-cache.json

# 播放速度变化后的延迟保存时间，单位秒；用于避免频繁写盘
save_delay=0.8

# 允许缓存/恢复的最小播放速度；低于此值会被忽略
min_speed=0.1

# 允许缓存/恢复的最大播放速度；高于此值会被忽略
max_speed=10
