# https://github.com/Koopex/uosc_history_menu

#==================================[ 脚本设置 ]====================================

# <zh>: 中文
# <en>: English
language=zh

#------------[ 打开mpv以后的动作 ]------------
# <resume>	恢复上次播放的文件
# <menu>	打开播放记录
# <none>	什么也不做
start_action=none

#---------------[ 文件夹续播 ]----------------
#  当你打开某文件夹中的一个视频时，如果同文件夹内有其他视频记录，
#  插件会弹出菜单询问你是否跳转续播。
# <yes>
# <no>
resume_in_folder=no

#---------------[ 条目标题 ]------------------
# <yes>	列表显示 文件名
# <no>	列表显示 媒体标题
filename=no

#--------------[ 搜索结果排序 ]---------------
# <yes>	搜索结果按播放时间排序
# <no>	uosc 默认的搜索结果
search_sorting=no

#-------------[ 记录文件路径 ]----------------
# ~~home 表示mpv.conf所在文件夹
log_path=~~home/uosc_history.json



#------------------------------------[ 快捷键 ]------------------------------------	
# r				script-binding uosc_history/history				#! 播放记录
# Alt+r			script-binding uosc_history/enable_history		#! 禁用 播放记录
# Ctrl+Alt+r	script-binding uosc_history/clear_history		#! 清空播放记录

# d				script-binding uosc_history/bookmarks			#! 收藏夹
# Ctrl+d		script-binding uosc_history/add_bookmarks		#! 添加收藏
# Alt+d			script-binding uosc_history/toggle_quick_mark	#! 切换快速收藏模式
# Ctrl+Alt+d	script-binding uosc_history/clear_bookmarks		#! 清空收藏夹
#----------------------------------------------------------------------------------

#--------------[ uosc按钮 ]--------------
# button:history		播放记录
# button:bookmarks		收藏夹
# button:add_bookmarks	添加收藏
#----------------------------------------
#===================================================================================
